### ISSUE TITLE
waht speed does this mode with 3090 or other latest GPU?

### ISSUE THREAD

**Issue by blazeCCC** [TuSimple/centerformer#13]
thank you for you excellent work, and i want to know waht speed does this mode with 3090 or other latest GPU? My gpu is very poor, so i want to know the speed with a better GPU.I would appreciate it if anyone could answer me .

**Comment by edwardzhou130** [comment]
I don't have access to 3090. But the inference time for the basic single-frame [CenterFormer](https://github.com/TuSimple/centerformer/blob/master/configs/waymo/voxelnet/waymo_centerformer.py) is 80.8ms on V100.

**Comment by blazeCCC** [comment]
> 

Thank you for you reply, i got a 3090 to test the 2 frames model and it  took about 120 ms.
