### ISSUE TITLE
About `disable_dbsampler`

### ISSUE THREAD

**Issue by junhocho** [TuSimple/centerformer#21]
Hi, I succesfully reproduced base centerformer 68.06 in nuscenes. 
Thanks a lot.

One thing I have noticed difference from CenterPoint base code is,
you code contains `disable_dbsampler` option.
Could you explain what's the motivation of this part? Is it simply turning off augmentation from epoch 15?

**Comment by edwardzhou130** [comment]
This is a training trick introduced by [Pointaugmenting](https://github.com/VISION-SJTU/PointAugmenting) and is commonly used in most recent papers. Basically, the final performance is better if we disable the copy & paste augmentation in the last few epochs. I actually have not tried numbers other than 15 in my experiments.

**Comment by junhocho** [comment]
Thakns a lot!
