### ISSUE TITLE
waymo coordinates

### ISSUE THREAD

**Issue by DezeZhao** [TuSimple/centerformer#29]
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/datasets/waymo/waymo_common.py#L269
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/datasets/waymo/waymo_common.py#L270

**Comment by DezeZhao** [comment]
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/models/bbox_heads/center_head_iou_1d.py#L506

**Comment by DezeZhao** [comment]
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/core/bbox/box_torch_ops.py#L256
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/core/bbox/box_torch_ops.py#L257

**Comment by DezeZhao** [comment]
@edwardzhou130, hello, can you help me about the question, thank you a lot. 
From codes all above, I know that waymo infos' gt boxes coordinates are` [xyzwlhr]`, and `r = -pi/2-r` for training and validating; but while calculating **iou_loss**, I see you again translate the **pred box** ang **gt box** to pcdet's coords like [xyzlwhr], but this time `r` should not  be `-pi/2-r` ? I think it should remain unchanged for gt box?
https://github.com/TuSimple/centerformer/blob/5a949b88ed7bb15aafb39bf78c95f1452063ebea/det3d/models/bbox_heads/center_head_iou_1d.py#L269
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/44592986/225008713-89caae9f-28c7-4a04-ae1e-0c5894198570.png">

**Comment by edwardzhou130** [comment]
I actually didn't look into this. I directly use their implementation to calculate the IoU. I think probably it's okay as long as the pred box and gt box are kept in their required format.
