### ISSUE TITLE
Code for nuScenes Dataset

### ISSUE THREAD

**Issue by Zhimin-C** [TuSimple/centerformer#3]
Thanks for your great work! The paper also provides nuScenes results in supplemental materials. May you upload codes for training in the nuScenes dataset? Thanks again.

**Comment by edwardzhou130** [comment]
Thanks for your interest in our work. The result we provided in the supplemental materials was from a simple version of CenterFormer, which only aims to demonstrate the improvement of our transformer structure. I still need to test it with some features in our paper (deformable attention/ multi-frame fusion) and find a more suitable training setting. I will add the codes for nuScenes once I complete those experiments.

**Comment by rockywind** [comment]
@edwardzhou130 
您好，有个问题请教一下哈。
怎么用nuscene数据集去调试，centerformer代码。手中暂时没有waymo数据集

**Comment by edwardzhou130** [comment]
@rockywind You can refer to CenterPoint's [configs](https://github.com/tianweiy/CenterPoint/tree/master/configs/nusc) for the training in nuScenes. What I did was simply switch the neck and bbox head to CenterFormer. 
Some notes: 1) Some modules and parameters that work well in Waymo may not work in nuScenes due to the difference in the data and evaluation method, like the IoU loss. https://github.com/TuSimple/centerformer/blob/0408b29fa728950baead73354e21240174ce5b6b/configs/waymo/voxelnet/waymo_centerformer.py#L59 2) Our released code currently does not support multi-task in the bbox head.

**Comment by rockywind** [comment]
@edwardzhou130 
您好，按照这个[教程](https://github.com/TuSimple/centerformer/blob/master/docs/INSTALL.md)安装，运行会报这个错。
```
  File "/DATA2/xiaoquan.wang/centerformer/det3d/models/detectors/voxelnet_dynamic.py", line 20, in __init__
    super(VoxelNet_dynamic, self).__init__(
  File "/DATA2/xiaoquan.wang/centerformer/det3d/models/detectors/single_stage.py", line 24, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/DATA2/xiaoquan.wang/centerformer/det3d/models/builder.py", line 35, in build_backbone
    return build(cfg, BACKBONES)
  File "/DATA2/xiaoquan.wang/centerformer/det3d/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/DATA2/xiaoquan.wang/centerformer/det3d/utils/registry.py", line 65, in build_from_cfg
    raise KeyError(
KeyError: 'SpMiddleResNetFHD is not in the backbone registry'
```

**Comment by dk-liang** [comment]
> 



> @edwardzhou130 您好，按照这个[教程](https://github.com/TuSimple/centerformer/blob/master/docs/INSTALL.md)安装，运行会报这个错。
> 
> ```
>   File "/DATA2/xiaoquan.wang/centerformer/det3d/models/detectors/voxelnet_dynamic.py", line 20, in __init__
>     super(VoxelNet_dynamic, self).__init__(
>   File "/DATA2/xiaoquan.wang/centerformer/det3d/models/detectors/single_stage.py", line 24, in __init__
>     self.backbone = builder.build_backbone(backbone)
>   File "/DATA2/xiaoquan.wang/centerformer/det3d/models/builder.py", line 35, in build_backbone
>     return build(cfg, BACKBONES)
>   File "/DATA2/xiaoquan.wang/centerformer/det3d/models/builder.py", line 21, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/DATA2/xiaoquan.wang/centerformer/det3d/utils/registry.py", line 65, in build_from_cfg
>     raise KeyError(
> KeyError: 'SpMiddleResNetFHD is not in the backbone registry'
> ```

You need to install spconv1.2.1
